/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed1;
  GtkWidget *fixed2;
  GtkWidget *identifiantaa;
  GtkWidget *motdepasseaa;
  GtkWidget *Mot_de_passe;
  GtkWidget *Identifiant_;
  GtkWidget *connexion_;
  GtkWidget *alignment10;
  GtkWidget *hbox13;
  GtkWidget *image10;
  GtkWidget *label42;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (authentification, 800, 765);
  gtk_window_set_title (GTK_WINDOW (authentification), _("authentification"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (authentification), fixed1);
  gtk_widget_set_size_request (fixed1, 0, 0);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed2, 264, 136);
  gtk_widget_set_size_request (fixed2, 50, 50);

  identifiantaa = gtk_entry_new ();
  gtk_widget_show (identifiantaa);
  gtk_fixed_put (GTK_FIXED (fixed1), identifiantaa, 344, 120);
  gtk_widget_set_size_request (identifiantaa, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiantaa), 8226);

  motdepasseaa = gtk_entry_new ();
  gtk_widget_show (motdepasseaa);
  gtk_fixed_put (GTK_FIXED (fixed1), motdepasseaa, 336, 176);
  gtk_widget_set_size_request (motdepasseaa, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (motdepasseaa), 8226);

  Mot_de_passe = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (Mot_de_passe);
  gtk_fixed_put (GTK_FIXED (fixed1), Mot_de_passe, 104, 176);
  gtk_widget_set_size_request (Mot_de_passe, 136, 32);

  Identifiant_ = gtk_label_new (_("Identifiant "));
  gtk_widget_show (Identifiant_);
  gtk_fixed_put (GTK_FIXED (fixed1), Identifiant_, 96, 112);
  gtk_widget_set_size_request (Identifiant_, 144, 32);

  connexion_ = gtk_button_new ();
  gtk_widget_show (connexion_);
  gtk_fixed_put (GTK_FIXED (fixed1), connexion_, 264, 320);
  gtk_widget_set_size_request (connexion_, 176, 45);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (connexion_), alignment10);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox13);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox13), image10, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("connexion "));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox13), label42, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) connexion_, "clicked",
                    G_CALLBACK (on_connexion__clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (authentification, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (authentification, identifiantaa, "identifiantaa");
  GLADE_HOOKUP_OBJECT (authentification, motdepasseaa, "motdepasseaa");
  GLADE_HOOKUP_OBJECT (authentification, Mot_de_passe, "Mot_de_passe");
  GLADE_HOOKUP_OBJECT (authentification, Identifiant_, "Identifiant_");
  GLADE_HOOKUP_OBJECT (authentification, connexion_, "connexion_");
  GLADE_HOOKUP_OBJECT (authentification, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (authentification, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (authentification, image10, "image10");
  GLADE_HOOKUP_OBJECT (authentification, label42, "label42");

  return authentification;
}

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed9;
  GtkWidget *table2;
  GtkWidget *Nom;
  GtkWidget *Prenom;
  GtkWidget *Identifiant;
  GtkWidget *Date_de_naissance;
  GtkWidget *Numero_de_cin;
  GtkWidget *Sexe;
  GtkWidget *Poste;
  GtkWidget *nomajouteraa;
  GtkWidget *prenomajouteraa;
  GtkWidget *identifiantajouteraa;
  GtkWidget *cinajouteraa;
  GtkWidget *combobox_poste2;
  GtkWidget *fixed10;
  GtkWidget *homme1;
  GSList *homme1_group = NULL;
  GtkWidget *femme1;
  GtkWidget *hbox4;
  GtkObject *jourajouteraa_adj;
  GtkWidget *jourajouteraa;
  GtkObject *moisajouteraa_adj;
  GtkWidget *moisajouteraa;
  GtkObject *anneajouteraa_adj;
  GtkWidget *anneajouteraa;
  GtkWidget *Retour;
  GtkWidget *alignment12;
  GtkWidget *hbox15;
  GtkWidget *image12;
  GtkWidget *label44;
  GtkWidget *Sauvegarder;
  GtkWidget *alignment4;
  GtkWidget *hbox5;
  GtkWidget *image4;
  GtkWidget *label22;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout, 800, 765);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("Ajouter"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed9);
  gtk_widget_set_size_request (fixed9, 540, -1);

  table2 = gtk_table_new (7, 2, FALSE);
  gtk_widget_show (table2);
  gtk_fixed_put (GTK_FIXED (fixed9), table2, 56, 0);
  gtk_widget_set_size_request (table2, 16, 16);

  Nom = gtk_label_new (_("Nom"));
  gtk_widget_show (Nom);
  gtk_table_attach (GTK_TABLE (table2), Nom, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Nom), 0, 0.5);

  Prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (Prenom);
  gtk_table_attach (GTK_TABLE (table2), Prenom, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Prenom), 0, 0.5);

  Identifiant = gtk_label_new (_("Identifiant"));
  gtk_widget_show (Identifiant);
  gtk_table_attach (GTK_TABLE (table2), Identifiant, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Identifiant), 0, 0.5);

  Date_de_naissance = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (Date_de_naissance);
  gtk_table_attach (GTK_TABLE (table2), Date_de_naissance, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Date_de_naissance), 0, 0.5);

  Numero_de_cin = gtk_label_new (_("Numero de cin "));
  gtk_widget_show (Numero_de_cin);
  gtk_table_attach (GTK_TABLE (table2), Numero_de_cin, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Numero_de_cin), 0, 0.5);

  Sexe = gtk_label_new (_("Sexe "));
  gtk_widget_show (Sexe);
  gtk_table_attach (GTK_TABLE (table2), Sexe, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Sexe), 0, 0.5);

  Poste = gtk_label_new (_("Poste "));
  gtk_widget_show (Poste);
  gtk_table_attach (GTK_TABLE (table2), Poste, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (Poste), 0, 0.5);

  nomajouteraa = gtk_entry_new ();
  gtk_widget_show (nomajouteraa);
  gtk_table_attach (GTK_TABLE (table2), nomajouteraa, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomajouteraa), 8226);

  prenomajouteraa = gtk_entry_new ();
  gtk_widget_show (prenomajouteraa);
  gtk_table_attach (GTK_TABLE (table2), prenomajouteraa, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomajouteraa), 8226);

  identifiantajouteraa = gtk_entry_new ();
  gtk_widget_show (identifiantajouteraa);
  gtk_table_attach (GTK_TABLE (table2), identifiantajouteraa, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiantajouteraa), 8226);

  cinajouteraa = gtk_entry_new ();
  gtk_widget_show (cinajouteraa);
  gtk_table_attach (GTK_TABLE (table2), cinajouteraa, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinajouteraa), 8226);

  combobox_poste2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_poste2);
  gtk_table_attach (GTK_TABLE (table2), combobox_poste2, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_poste2), _("technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_poste2), _("nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_poste2), _("agent du foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_poste2), _("agent du restaurant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_poste2), _("etudiant"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_table_attach (GTK_TABLE (table2), fixed10, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  homme1 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (homme1);
  gtk_fixed_put (GTK_FIXED (fixed10), homme1, 0, 0);
  gtk_widget_set_size_request (homme1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (homme1), homme1_group);
  homme1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (homme1));

  femme1 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (femme1);
  gtk_fixed_put (GTK_FIXED (fixed10), femme1, 104, 0);
  gtk_widget_set_size_request (femme1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femme1), homme1_group);
  homme1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femme1));

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_table_attach (GTK_TABLE (table2), hbox4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  jourajouteraa_adj = gtk_adjustment_new (2, 1, 31, 1, 10, 10);
  jourajouteraa = gtk_spin_button_new (GTK_ADJUSTMENT (jourajouteraa_adj), 1, 0);
  gtk_widget_show (jourajouteraa);
  gtk_box_pack_start (GTK_BOX (hbox4), jourajouteraa, TRUE, TRUE, 0);

  moisajouteraa_adj = gtk_adjustment_new (12, 1, 12, 1, 10, 10);
  moisajouteraa = gtk_spin_button_new (GTK_ADJUSTMENT (moisajouteraa_adj), 1, 0);
  gtk_widget_show (moisajouteraa);
  gtk_box_pack_start (GTK_BOX (hbox4), moisajouteraa, TRUE, TRUE, 0);

  anneajouteraa_adj = gtk_adjustment_new (1910, 1910, 2030, 1, 10, 10);
  anneajouteraa = gtk_spin_button_new (GTK_ADJUSTMENT (anneajouteraa_adj), 1, 0);
  gtk_widget_show (anneajouteraa);
  gtk_box_pack_start (GTK_BOX (hbox4), anneajouteraa, TRUE, TRUE, 0);

  Retour = gtk_button_new ();
  gtk_widget_show (Retour);
  gtk_fixed_put (GTK_FIXED (fixed9), Retour, 224, 240);
  gtk_widget_set_size_request (Retour, 176, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (Retour), alignment12);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox15);

  image12 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox15), image12, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_(" Retour"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox15), label44, FALSE, FALSE, 0);

  Sauvegarder = gtk_button_new ();
  gtk_widget_show (Sauvegarder);
  gtk_fixed_put (GTK_FIXED (fixed9), Sauvegarder, 16, 240);
  gtk_widget_set_size_request (Sauvegarder, 176, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Sauvegarder), alignment4);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox5);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox5), image4, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_(" Sauvegarder"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox5), label22, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) homme1, "toggled",
                    G_CALLBACK (on_homme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) femme1, "toggled",
                    G_CALLBACK (on_femme1_toggled),
                    NULL);
  g_signal_connect ((gpointer) Sauvegarder, "clicked",
                    G_CALLBACK (on_Sauvegarder_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Ajout, table2, "table2");
  GLADE_HOOKUP_OBJECT (Ajout, Nom, "Nom");
  GLADE_HOOKUP_OBJECT (Ajout, Prenom, "Prenom");
  GLADE_HOOKUP_OBJECT (Ajout, Identifiant, "Identifiant");
  GLADE_HOOKUP_OBJECT (Ajout, Date_de_naissance, "Date_de_naissance");
  GLADE_HOOKUP_OBJECT (Ajout, Numero_de_cin, "Numero_de_cin");
  GLADE_HOOKUP_OBJECT (Ajout, Sexe, "Sexe");
  GLADE_HOOKUP_OBJECT (Ajout, Poste, "Poste");
  GLADE_HOOKUP_OBJECT (Ajout, nomajouteraa, "nomajouteraa");
  GLADE_HOOKUP_OBJECT (Ajout, prenomajouteraa, "prenomajouteraa");
  GLADE_HOOKUP_OBJECT (Ajout, identifiantajouteraa, "identifiantajouteraa");
  GLADE_HOOKUP_OBJECT (Ajout, cinajouteraa, "cinajouteraa");
  GLADE_HOOKUP_OBJECT (Ajout, combobox_poste2, "combobox_poste2");
  GLADE_HOOKUP_OBJECT (Ajout, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Ajout, homme1, "homme1");
  GLADE_HOOKUP_OBJECT (Ajout, femme1, "femme1");
  GLADE_HOOKUP_OBJECT (Ajout, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Ajout, jourajouteraa, "jourajouteraa");
  GLADE_HOOKUP_OBJECT (Ajout, moisajouteraa, "moisajouteraa");
  GLADE_HOOKUP_OBJECT (Ajout, anneajouteraa, "anneajouteraa");
  GLADE_HOOKUP_OBJECT (Ajout, Retour, "Retour");
  GLADE_HOOKUP_OBJECT (Ajout, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Ajout, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Ajout, image12, "image12");
  GLADE_HOOKUP_OBJECT (Ajout, label44, "label44");
  GLADE_HOOKUP_OBJECT (Ajout, Sauvegarder, "Sauvegarder");
  GLADE_HOOKUP_OBJECT (Ajout, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Ajout, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Ajout, image4, "image4");
  GLADE_HOOKUP_OBJECT (Ajout, label22, "label22");

  return Ajout;
}

GtkWidget*
create_Modification_ (void)
{
  GtkWidget *Modification_;
  GtkWidget *fixed11;
  GtkWidget *non;
  GtkWidget *alignment14;
  GtkWidget *hbox17;
  GtkWidget *image14;
  GtkWidget *label46;
  GtkWidget *oui;
  GtkWidget *alignment13;
  GtkWidget *hbox16;
  GtkWidget *image13;
  GtkWidget *label45;
  GtkWidget *table3;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *identifiantmodificationaa;
  GtkWidget *nommodificationaa;
  GtkWidget *cinmodificationaa;
  GtkWidget *combobox_modification;
  GtkWidget *fixed12;
  GtkWidget *homme2;
  GSList *homme2_group = NULL;
  GtkWidget *femme2;
  GSList *femme2_group = NULL;
  GtkWidget *hbox7;
  GtkObject *jourmodificationaa_adj;
  GtkWidget *jourmodificationaa;
  GtkObject *moismodificationaa_adj;
  GtkWidget *moismodificationaa;
  GtkObject *anneemodificationaa_adj;
  GtkWidget *anneemodificationaa;
  GtkWidget *prenommodificationaa;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label49;

  Modification_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Modification_, 800, 765);
  gtk_window_set_title (GTK_WINDOW (Modification_), _("Modification "));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (Modification_), fixed11);

  non = gtk_button_new ();
  gtk_widget_show (non);
  gtk_fixed_put (GTK_FIXED (fixed11), non, 312, 448);
  gtk_widget_set_size_request (non, 176, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (non), alignment14);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox17);

  image14 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox17), image14, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_(" non"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox17), label46, FALSE, FALSE, 0);

  oui = gtk_button_new ();
  gtk_widget_show (oui);
  gtk_fixed_put (GTK_FIXED (fixed11), oui, 72, 448);
  gtk_widget_set_size_request (oui, 176, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (oui), alignment13);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox16);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox16), image13, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("oui"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox16), label45, FALSE, FALSE, 0);

  table3 = gtk_table_new (7, 2, FALSE);
  gtk_widget_show (table3);
  gtk_fixed_put (GTK_FIXED (fixed11), table3, 88, 40);
  gtk_widget_set_size_request (table3, 454, 474);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 15);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 17);

  label27 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table3), label27, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  label28 = gtk_label_new (_("Numero de cin "));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table3), label28, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);

  label29 = gtk_label_new (_("Sexe "));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table3), label29, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("Poste "));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table3), label30, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  identifiantmodificationaa = gtk_entry_new ();
  gtk_widget_show (identifiantmodificationaa);
  gtk_table_attach (GTK_TABLE (table3), identifiantmodificationaa, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiantmodificationaa), 8226);

  nommodificationaa = gtk_entry_new ();
  gtk_widget_show (nommodificationaa);
  gtk_table_attach (GTK_TABLE (table3), nommodificationaa, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (nommodificationaa), 8226);

  cinmodificationaa = gtk_entry_new ();
  gtk_widget_show (cinmodificationaa);
  gtk_table_attach (GTK_TABLE (table3), cinmodificationaa, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinmodificationaa), 8226);

  combobox_modification = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_modification);
  gtk_table_attach (GTK_TABLE (table3), combobox_modification, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modification), _("technicien"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modification), _("nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modification), _("l\342\200\231agent du foyer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modification), _("l\342\200\231agent du restaurant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modification), _("\303\251tudiants"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_table_attach (GTK_TABLE (table3), fixed12, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  homme2 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (homme2);
  gtk_fixed_put (GTK_FIXED (fixed12), homme2, 0, 0);
  gtk_widget_set_size_request (homme2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (homme2), homme2_group);
  homme2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (homme2));

  femme2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (femme2);
  gtk_fixed_put (GTK_FIXED (fixed12), femme2, 104, 8);
  gtk_widget_set_size_request (femme2, 112, 16);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femme2), femme2_group);
  femme2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femme2));

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_table_attach (GTK_TABLE (table3), hbox7, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  jourmodificationaa_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jourmodificationaa = gtk_spin_button_new (GTK_ADJUSTMENT (jourmodificationaa_adj), 1, 0);
  gtk_widget_show (jourmodificationaa);
  gtk_box_pack_start (GTK_BOX (hbox7), jourmodificationaa, TRUE, TRUE, 0);

  moismodificationaa_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  moismodificationaa = gtk_spin_button_new (GTK_ADJUSTMENT (moismodificationaa_adj), 1, 0);
  gtk_widget_show (moismodificationaa);
  gtk_box_pack_start (GTK_BOX (hbox7), moismodificationaa, TRUE, TRUE, 0);

  anneemodificationaa_adj = gtk_adjustment_new (1910, 1910, 2030, 1, 10, 10);
  anneemodificationaa = gtk_spin_button_new (GTK_ADJUSTMENT (anneemodificationaa_adj), 1, 0);
  gtk_widget_show (anneemodificationaa);
  gtk_box_pack_start (GTK_BOX (hbox7), anneemodificationaa, TRUE, TRUE, 0);

  prenommodificationaa = gtk_entry_new ();
  gtk_widget_show (prenommodificationaa);
  gtk_table_attach (GTK_TABLE (table3), prenommodificationaa, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenommodificationaa), 8226);

  label47 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table3), label47, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  label48 = gtk_label_new (_("Nom"));
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table3), label48, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  label49 = gtk_label_new (_("<span foreground=\"red\">IDENIFIANT</span>"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table3), label49, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  g_signal_connect ((gpointer) non, "clicked",
                    G_CALLBACK (on_non_clicked),
                    NULL);
  g_signal_connect ((gpointer) oui, "clicked",
                    G_CALLBACK (on_oui_clicked),
                    NULL);
  g_signal_connect ((gpointer) homme2, "toggled",
                    G_CALLBACK (on_homme2_toggled),
                    NULL);
  g_signal_connect ((gpointer) femme2, "toggled",
                    G_CALLBACK (on_femme2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modification_, Modification_, "Modification_");
  GLADE_HOOKUP_OBJECT (Modification_, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Modification_, non, "non");
  GLADE_HOOKUP_OBJECT (Modification_, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Modification_, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Modification_, image14, "image14");
  GLADE_HOOKUP_OBJECT (Modification_, label46, "label46");
  GLADE_HOOKUP_OBJECT (Modification_, oui, "oui");
  GLADE_HOOKUP_OBJECT (Modification_, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Modification_, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Modification_, image13, "image13");
  GLADE_HOOKUP_OBJECT (Modification_, label45, "label45");
  GLADE_HOOKUP_OBJECT (Modification_, table3, "table3");
  GLADE_HOOKUP_OBJECT (Modification_, label27, "label27");
  GLADE_HOOKUP_OBJECT (Modification_, label28, "label28");
  GLADE_HOOKUP_OBJECT (Modification_, label29, "label29");
  GLADE_HOOKUP_OBJECT (Modification_, label30, "label30");
  GLADE_HOOKUP_OBJECT (Modification_, identifiantmodificationaa, "identifiantmodificationaa");
  GLADE_HOOKUP_OBJECT (Modification_, nommodificationaa, "nommodificationaa");
  GLADE_HOOKUP_OBJECT (Modification_, cinmodificationaa, "cinmodificationaa");
  GLADE_HOOKUP_OBJECT (Modification_, combobox_modification, "combobox_modification");
  GLADE_HOOKUP_OBJECT (Modification_, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Modification_, homme2, "homme2");
  GLADE_HOOKUP_OBJECT (Modification_, femme2, "femme2");
  GLADE_HOOKUP_OBJECT (Modification_, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Modification_, jourmodificationaa, "jourmodificationaa");
  GLADE_HOOKUP_OBJECT (Modification_, moismodificationaa, "moismodificationaa");
  GLADE_HOOKUP_OBJECT (Modification_, anneemodificationaa, "anneemodificationaa");
  GLADE_HOOKUP_OBJECT (Modification_, prenommodificationaa, "prenommodificationaa");
  GLADE_HOOKUP_OBJECT (Modification_, label47, "label47");
  GLADE_HOOKUP_OBJECT (Modification_, label48, "label48");
  GLADE_HOOKUP_OBJECT (Modification_, label49, "label49");

  return Modification_;
}

GtkWidget*
create_Suppression_ (void)
{
  GtkWidget *Suppression_;
  GtkWidget *fixed13;
  GtkWidget *button9;
  GtkWidget *alignment9;
  GtkWidget *hbox12;
  GtkWidget *image9;
  GtkWidget *label41;
  GtkWidget *buttonconfirmer;
  GtkWidget *alignment8;
  GtkWidget *hbox11;
  GtkWidget *image8;
  GtkWidget *label40;
  GtkWidget *label51;
  GtkWidget *entrysupp;

  Suppression_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Suppression_, 800, 765);
  gtk_window_set_title (GTK_WINDOW (Suppression_), _("Suppression "));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (Suppression_), fixed13);
  gtk_widget_set_size_request (fixed13, 540, -1);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed13), button9, 224, 240);
  gtk_widget_set_size_request (button9, 176, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9), alignment9);
  gtk_widget_set_size_request (alignment9, 49, 17);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox12);

  image9 = gtk_image_new_from_stock ("gtk-stop", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox12), image9, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox12), label41, FALSE, FALSE, 0);

  buttonconfirmer = gtk_button_new ();
  gtk_widget_show (buttonconfirmer);
  gtk_fixed_put (GTK_FIXED (fixed13), buttonconfirmer, 16, 240);
  gtk_widget_set_size_request (buttonconfirmer, 176, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonconfirmer), alignment8);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox11);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox11), image8, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox11), label40, FALSE, FALSE, 0);

  label51 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed13), label51, 40, 56);
  gtk_widget_set_size_request (label51, 160, 49);

  entrysupp = gtk_entry_new ();
  gtk_widget_show (entrysupp);
  gtk_fixed_put (GTK_FIXED (fixed13), entrysupp, 184, 64);
  gtk_widget_set_size_request (entrysupp, 192, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrysupp), 8226);

  g_signal_connect ((gpointer) buttonconfirmer, "clicked",
                    G_CALLBACK (on_buttonconfirmer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Suppression_, Suppression_, "Suppression_");
  GLADE_HOOKUP_OBJECT (Suppression_, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Suppression_, button9, "button9");
  GLADE_HOOKUP_OBJECT (Suppression_, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Suppression_, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Suppression_, image9, "image9");
  GLADE_HOOKUP_OBJECT (Suppression_, label41, "label41");
  GLADE_HOOKUP_OBJECT (Suppression_, buttonconfirmer, "buttonconfirmer");
  GLADE_HOOKUP_OBJECT (Suppression_, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Suppression_, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Suppression_, image8, "image8");
  GLADE_HOOKUP_OBJECT (Suppression_, label40, "label40");
  GLADE_HOOKUP_OBJECT (Suppression_, label51, "label51");
  GLADE_HOOKUP_OBJECT (Suppression_, entrysupp, "entrysupp");

  return Suppression_;
}

GtkWidget*
create_liste_des_utilisateurs (void)
{
  GtkWidget *liste_des_utilisateurs;
  GtkWidget *fixed15;
  GtkWidget *treeview1;
  GtkWidget *Gestion_des_utilisateurs;
  GtkWidget *Ajouter;
  GtkWidget *Supprimer;
  GtkWidget *Modifier;
  GtkWidget *button11;
  GtkWidget *alignment15;
  GtkWidget *hbox18;
  GtkWidget *image15;
  GtkWidget *label50;

  liste_des_utilisateurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (liste_des_utilisateurs, 800, 765);
  gtk_window_set_title (GTK_WINDOW (liste_des_utilisateurs), _("liste des utilisateurs "));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (liste_des_utilisateurs), fixed15);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed15), treeview1, 32, 80);
  gtk_widget_set_size_request (treeview1, 592, 280);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 5);

  Gestion_des_utilisateurs = gtk_label_new (_("Gestion des utilisateurs"));
  gtk_widget_show (Gestion_des_utilisateurs);
  gtk_fixed_put (GTK_FIXED (fixed15), Gestion_des_utilisateurs, 120, 24);
  gtk_widget_set_size_request (Gestion_des_utilisateurs, 160, 23);

  Ajouter = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (Ajouter);
  gtk_fixed_put (GTK_FIXED (fixed15), Ajouter, 24, 368);
  gtk_widget_set_size_request (Ajouter, 82, 32);

  Supprimer = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (Supprimer);
  gtk_fixed_put (GTK_FIXED (fixed15), Supprimer, 208, 368);
  gtk_widget_set_size_request (Supprimer, 96, 32);

  Modifier = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (Modifier);
  gtk_fixed_put (GTK_FIXED (fixed15), Modifier, 120, 368);
  gtk_widget_set_size_request (Modifier, 80, 32);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed15), button11, 120, 416);
  gtk_widget_set_size_request (button11, 112, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button11), alignment15);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox18);

  image15 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox18), image15, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox18), label50, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Ajouter, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) Supprimer, "clicked",
                    G_CALLBACK (on_Supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier, "clicked",
                    G_CALLBACK (on_Modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_des_utilisateurs, liste_des_utilisateurs, "liste_des_utilisateurs");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, Gestion_des_utilisateurs, "Gestion_des_utilisateurs");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, button11, "button11");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, image15, "image15");
  GLADE_HOOKUP_OBJECT (liste_des_utilisateurs, label50, "label50");

  return liste_des_utilisateurs;
}

