/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_Ajout (void);
GtkWidget* create_Modification_ (void);
GtkWidget* create_Suppression_ (void);
GtkWidget* create_liste_des_utilisateurs (void);
