/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *authentification;
  GtkWidget *Ajout;
  GtkWidget *Modification_;
  GtkWidget *Suppression_;
  GtkWidget *liste_des_utilisateurs;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  authentification = create_authentification ();
  gtk_widget_show (authentification);
  Ajout = create_Ajout ();
  gtk_widget_show (Ajout);
  Modification_ = create_Modification_ ();
  gtk_widget_show (Modification_);
  Suppression_ = create_Suppression_ ();
  gtk_widget_show (Suppression_);
  liste_des_utilisateurs = create_liste_des_utilisateurs ();
  gtk_widget_show (liste_des_utilisateurs);

  gtk_main ();
  return 0;
}

